
name: 'jal_tech'
version: '1.0.0'

profile: 'jal_tech'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:      
  - "target"
  - "dbt_packages" 




models:
  jal_tech:
    example:
      +materialized: view
models:
